### ISSUE TITLE
Connecting to Spark from Jupyter problem

### ISSUE THREAD

**Issue by ThatBeardedDude** [radanalyticsio/openshift-spark#62] opened 2018-08-21 11:53 UTC
Once again I'm experiencing an issue that is not specifically about the Openshift-Spark itself. Instead it is related to connecting from a Jupyter notebook, opened via Jupyterhub in one Openshift project, to a Spark cluster opened via Oshinko web UI in another Openshift project - each project belong to different people.
Have you ever experienced similar problems?
Is this a problem that sould even be considered an issue in this repo?

**Comment by elmiko** [comment] 2018-08-21 12:14
i don't think this is a good place for the issue you are experiencing, but i can shed some light into your problem.

so, firstly having the spark cluster in project "A" and a notebook in project "B" will present problems from the perspective of needing to open project A's pod network so that project B can see it. since all the nodes of the spark cluster will need to communicate with the notebook this can get hairy.

you will definitely want to use something like pod network joining command: https://docs.okd.io/3.10/admin_guide/managing_networking.html#joining-project-networks

as a general principle, the radanalytics/oshinko way of doing this is to always spawn spark clusters in the local project. so, in most cases we advise against this type of behavior.

the second issue you will experience is that in spark 2.3+ the worker nodes need to have fqdn information to get back to the driver node(the notebook in this case). to make this work you will need to expose extra ports on your notebook pod and then configure the spark cluster to talk properly back to the notebook.

i have done a little experimentation in this area, you can see a post with my results here https://elmiko.github.io/2018/08/05/attaching-notebooks-with-radanalytics.html

now for the really complicated part, note that my article is about spark 2.2, for this to work with spark 2.3 and the oshinko stuff you will most likely want to copy the pattern we have start using a "headless" service to the driver (notebook) pod. see https://github.com/radanalyticsio/radanalyticsio.github.io/blob/master/resources.yaml#L560 for an example. this headless service will become the new "spark.driver.host" that needs to be configured in the spark cluster.

see the bottom of this post, https://elmiko.github.io/2018/05/18/python3-coming-to-radanalytics.html , for some hints.

i realize this is quite long winded, but as you can see this problem is note quite as simple as just plugging things in. i really hope we can automate some of this in a future radanalytics release. but for now, i do not think this is proper repo to report on. i am going to mark this as closed.

**Comment by elmiko** [comment] 2018-08-21 12:15
closing this issue as it is out of scope for the spark image

**Closed by elmiko** 2018-08-21 12:15 UTC
Labels: invalid, question

**Comment by ThatBeardedDude** [comment] 2018-08-21 12:53
Thank you very much for the extremely detailed answer! I'll look into
everything you sent.

**Comment by Sushmamanjunath** [comment] 2019-03-14 20:33
Thank you for your work on Openshift. I am trying to connect a Jupyter notebook running in the same project to a spark master and slaves (spark standalone cluster) running in pods on Openshift. I have one master and two slaves. and the slaves are visible through the Spark UI. However I am running into the problem you detail here: the spark workers need the fqdn of the driver to talk back to it. I tried running jobs from the spark master and the jupyter pod and they both fail. The worker logs show this:
Caused by: org.apache.spark.rpc.RpcTimeoutException: Cannot receive any reply from spark:8998 in 120 seconds. This timeout is controlled by spark.rpc.askTimeout
spark is the name of the service in the same namespace and I exposed 8998 as well...
The log shows the executor command as:
Spark Executor Command: "/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.201.b09-0.el7_6.x86_64/jre/bin/java" "-cp" "/opt/spark/conf/:/opt/spark/jars/*" "-Xmx1024M" "-Dspark.driver.port=8998" "org.apache.spark.executor.CoarseGrainedExecutorBackend" "--driver-url" "spark://CoarseGrainedScheduler@spark:8998" "--executor-id" "3" "--hostname" "10.131.81.83" "--cores" "1" "--app-id" "app-20190314195130-0001" "--worker-url" "spark://Worker@10.131.81.83:43692"

I thought setting the bind address to the POD_IP and the driver host to the service in the namespace would help the worker find the driver pod but I was wrong. How do I go about finding the FQDN of the driver pod in openshift and is it sufficient to pass it in the spark conf?

On a side note, running the the same on the spark worker succeeds as expected.

Thanks for your time and help.
-Sushma

**Comment by elmiko** [comment] 2019-03-14 20:54
hi Sushma,

i have a couple questions,

1. what version of spark are you using?
1. is your driver pod (the notebook iiuc) exposing port 8998 as the spark listener?
1. what is the `spark` service attached to, is it the spark master or the notebook(the driver)?
1. have you tried these [instructions from my blog](https://elmiko.github.io/2018/08/05/attaching-notebooks-with-radanalytics.html) ? i was able to pass the service for the driver (the notebook) to the workers as the host name and it worked, although i did need to expose the spark api port as well (7077).

> I thought setting the bind address to the POD_IP and the driver host to the service in the namespace would help the worker find the driver pod but I was wrong. How do I go about finding the FQDN of the driver pod in openshift and is it sufficient to pass it in the spark conf?

i did not have to set the bind addresses for the worker pods, the main key was to make sure that all the spark nodes (master and workers) had the `spark.driver.host` configuration set to the service from the driver (the notebook service).

as for the fqdn of the driver pod, i'm not sure there is one for each pod but for the service associated with it you can use the openshift cluster fqdn which should be in the form `<service name>.<project name>.svc`. i have used this successfully in the past. (assuming everything is in the same project this address should be resolvable, cross-project might need permissions based on the networking module)

things changed a little in spark 2.3, but i know the service name approach will work with spark 2.2 and we have several images in the radanalytics.io project that will work together.

**Comment by elmiko** [comment] 2019-03-14 21:01
one more followup, check out the [bottom of this blog post](https://elmiko.github.io/2018/05/18/python3-coming-to-radanalytics.html) to see how i made this work with spark 2.3

**Comment by Sushmamanjunath** [comment] 2019-03-14 22:37
I am using spark2.4. Spark service is attached to master.

I left the notebook pod till I can get the spark jobs working from the master at least. I do have a spark driver installed on the notebook pod so I can expose 8998 port when I am ready to move to it and run jobs from jupyter. For now, I am running the spark jobs from the spark master. So master is the driver as well.

So now, we have a spark master: spark://spark:7077. I have exposed a bunch of ports on spark master and workers: 7077,8080,8998 and 6066.
Spark master spark://10.128.211.77:7077

Two spark nodes running:
worker-20190314193902-10.131.81.83-43692<https://spark-platformteam.zipline-apps.aap.dl-preprod01.aws.discoverfinancial.com/proxy/worker-20190314193902-10.131.81.83-43692>  10.131.81.83:43692
worker-20190314193917-10.131.89.117-34780<https://spark-platformteam.zipline-apps.aap.dl-preprod01.aws.discoverfinancial.com/proxy/worker-20190314193917-10.131.89.117-34780> 10.131.89.117:34780

I executed pyspark with this as the conf for spark context on the spark master:

[('spark.ui.reverseProxyUrl', '/'), ('spark.master', 'spark://spark:7077'), ('spark.ui.proxyBase', '/proxy/app-20190314220627-0003'), ('spark.executor.id', 'driver'), ('spark.app.name', 'PySparkShell'), ('spark.app.id', 'app-20190314220733-0004'), ('spark.rdd.compress', 'True'), ('spark.driver.host', 'spark.platformteam.svc.cluster.local'), ('spark.driver.port', '8998'), ('spark.serializer.objectStreamReset', '100'), ('spark.driver.bindAddress', '10.128.211.77'), ('spark.submit.deployMode', 'client'), ('spark.ui.showConsoleProgress', 'true'), ('spark.ui.reverseProxy', 'true')]


On the first worker: the executor is showing the command as:
Spark Executor Command: "/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.201.b09-0.el7_6.x86_64/jre/bin/java" "-cp" "/opt/spark/conf/:/opt/spark/jars/*" "-Xmx1024M" "-Dspark.driver.port=8998" "org.apache.spark.executor.CoarseGrainedExecutorBackend" "--driver-url" "spark://CoarseGrainedScheduler@spark:8998" "--executor-id" "0" "--hostname" "10.131.81.83" "--cores" "1" "--app-id" "app-20190314220733-0004" "--worker-url" "spark://Worker@10.131.81.83:43692"

ping spark
PING spark.platformteam.svc.cluster.local (172.30.99.36) 56(84) bytes of data.
From 10.3.72.188 (10.3.72.188) icmp_seq=1 Time to live exceeded
From 10.3.72.188 (10.3.72.188) icmp_seq=2 Time to live exceeded
From 10.3.72.188 (10.3.72.188) icmp_seq=3 Time to live exceeded
From 10.3.72.188 (10.3.72.188) icmp_seq=4 Time to live exceeded
From 10.3.72.188 (10.3.72.188) icmp_seq=5 Time to live exceeded
From 10.3.72.188 (10.3.72.188) icmp_seq=6 Time to live exceeded
From 10.3.72.188 (10.3.72.188) icmp_seq=7 Time to live exceeded
^C
--- spark.platformteam.svc.cluster.local ping statistics ---
7 packets transmitted, 0 received, +7 errors, 100% packet loss, time 15048ms

ping is not working either on the spark slaves. So the spark slave is not seeing the driver.

Maybe I should revert to spark 2.2 and see if this works.

Thanks for sharing the blog.. I have been on them considerably. ☺

Sushma

**Comment by elmiko** [comment] 2019-03-14 23:10
> So now, we have a spark master: spark://spark:7077. I have exposed a bunch of ports on spark master and workers: 7077,8080,8998 and 6066. Spark master spark://10.128.211.77:7077

ok, so given this and the commands you show. if i assume that all other defaults are normal and you are running pyspark from the master (meaning it is the driver) then you should set the `spark.driver.host = spark` and `spark.driver.port = 7077`. you shouldn't need to set the port but just in case.

on the driver (the master in this case), you will want to set the `spark.driver.bindAddress = 0.0.0.0`, this probably isn't necessary but just in case.

i _think_ those settings should get you back on track, but i am only guessing ;)

**Comment by Sushmamanjunath** [comment] 2019-03-19 19:06
Thanks so much for your help!

I was able to use the driver address and the bindAddress and get spark jobs working on my spark standalone cluster. What I found in my environment is that for some reason, the spark slave is not communicating to the master through the service. Using the service spark or the spark.platformteam.svc.cluster.local neither works even though it is in the same namespace. I had to use the POD_IP as my driver.host for the slave to find the driver.

Anyway, long story short, I was able to run spark jobs from the spark master as well as a container that had Rstudio (using sparklyr, of course). I tried using the jupyter container and just can’t get it to work. Well, I am able to run pyspark from the terminal and the container user (user python ; locally defined in the /etc/passwd) is able to run spark jobs. But when I ldap auth into jupyter and try, pyspark fails. It can’t seem to get the Java gateway started.

/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pyspark/java_gateway.py in launch_gateway(conf)
     92
     93             if not os.path.isfile(conn_info_file):
---> 94                 raise Exception("Java gateway process exited before sending its port number")
     95
     96             with open(conn_info_file, "rb") as info:

Exception: Java gateway process exited before sending its port number

Is there a way to run jupyter as a local user in the container but still run spark jobs as an ldap authenticated user? Is my only option to run jupyter as the ldap user using the blog Jupyter as assigned id as inspiration?

PS: I don’t think this is a spark cluster problem. I tried the local spark on the jupyter container and same problems there as well.

Appreciate your insights.

Thanks!
Sushma

**Comment by elmiko** [comment] 2019-03-19 19:11
> Is there a way to run jupyter as a local user in the container but still run spark jobs as an ldap authenticated user? Is my only option to run jupyter as the ldap user using the blog Jupyter as assigned id as inspiration?

this is a great question that i wish i could answer. i have not tried using jupyter in this manner with the ldap authenticated user. i would imagine there is some way to do it (as with most things), but i am unfamiliar with how to do it.
